name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
- push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.9'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Test Columns
      id: test-columns
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Columns
        setup-command: ''
        command: python -m unittest tests/testColumns.py
        timeout: 1
        max-score: 1
    - name: Test Latitude
      id: test-lat
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Latitude
        setup-command: ''
        command: python -m unittest tests/testLatitude.py
        timeout: 1
        max-score: 1
    - name: Test Longitude
      id: test-lon
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Longitude
        setup-command: ''
        command: python -m unittest tests/testLongitude.py
        timeout: 1
        max-score: 1
    - name: Test Map
      id: test-map
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Map
        setup-command: ''
        command: python -m unittest tests/testMap.py
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-COLUMNS_RESULTS: "${{steps.test-columns.outputs.result}}"
        TEST-LAT_RESULTS: "${{steps.test-lat.outputs.result}}"
        TEST-LON_RESULTS: "${{steps.test-lon.outputs.result}}"
        TEST-MAP_RESULTS: "${{steps.test-map.outputs.result}}"
      with:
        runners: test-columns,test-lat,test-lon,test-map
